#!/usr/bin/perl
use strict;
use warnings;

# Advanced RSS Processor for Cross-Platform Streaming
# Dynamically handles thumbnails and direct-link streaming for Feeder/Mobile readers.

my $placeholder_url = $ARGV[0] || die "Missing placeholder URL\n";

undef $/;
my $xml_content = <STDIN>;

if (defined $xml_content && $xml_content ne "") {
    $xml_content =~ s/<item>(.*?)<\/item>/process_item($1, $placeholder_url)/gse;
    print $xml_content;
}

sub process_item {
    my ($item_body, $placeholder) = @_;
    
    # Strip old enclosures to avoid confusion in the reader
    $item_body =~ s/<enclosure[^>]*>//gi;
    
    # Extract the localized GitHub URL to identify the media hash
    # This regex is flexible and adapts to any repo/username structure
    if ($item_body =~ m{(https://raw\.githubusercontent\.com/([^/]+)/([^/]+)/[^\s"<]+/feeds/media/([a-f0-9]+)\.([a-zA-Z0-9]+))}i) {
        my $full_url = $1;
        my $user     = $2;
        my $repo     = $3;
        my $hash     = $4;
        my $ext      = lc($5);
        
        my $base_raw = "https://raw.githubusercontent.com/$user/$repo/main/feeds/media";
        my $thumb_url = "$base_raw/$hash.thumb.jpg";
        my $stream_url = "$base_raw/$hash.$ext";

        # MIME Mapping
        my %mimes = ( 'mp4'=>'video/mp4', 'mp3'=>'audio/mpeg', 'jpg'=>'image/jpeg', 'png'=>'image/png', 'gif'=>'video/mp4' );
        my $mime = $mimes{$ext} || "application/octet-stream";

        my $display_img = $placeholder;
        my $action_button = "";

        if ($ext eq "jpg" || $ext eq "png") {
            $display_img = $stream_url;
        } else {
            # Check if a thumbnail was generated by the bridge
            # Note: In a static RSS, we assume it exists if it's a video/audio
            $display_img = $thumb_url;
            
            my $type_label = ($ext eq "mp4") ? "VIDEO" : ($ext eq "mp3") ? "AUDIO/PODCAST" : "MEDIA";
            
            # Professional Call-to-Action for Streaming
            $action_button = <<EOF;
<div style="margin-top:10px; padding:12px; background:#007bff; border-radius:8px; text-align:center;">
    <a href="$stream_url" style="color:#ffffff; text-decoration:none; font-family:sans-serif; font-weight:bold; display:block;">
        🚀 STREAM $type_label NOW
    </a>
</div>
<p style="font-size:11px; color:#666; text-align:center;">Click to open in your system player</p>
EOF
        }

        # Construct Description: Thumbnail first, then the Action Button, then the original text
        my $new_desc = <<EOF;
<img src="$display_img" style="width:100%; border-radius:12px; display:block; margin-bottom:10px;" />
$action_button
<br/>
EOF
        
        # Inject into CDATA
        $item_body =~ s/<description>\s*<!\[CDATA\[/<description><![CDATA[$new_desc/;
        
        # Set Enclosure to the actual STREAMABLE file (MP4/MP3)
        return "<item>$item_body<enclosure url=\"$stream_url\" type=\"$mime\" length=\"1024000\" /></item>";
    }

    # Fallback for text-only posts
    $item_body =~ s/<description>\s*<!\[CDATA\[/<description><![CDATA[<img src="$placeholder" style="width:100%; border-radius:12px; margin-bottom:10px;" \/><br\/>/;
    return "<item>$item_body<enclosure url=\"$placeholder\" type=\"image/jpeg\" length=\"51200\" /></item>";
}
